name: flutter_style_transfer
description: Flutter image style transfer
publish_to: 'none'
version: 1.0.0
repository: https://github.com/ame-yu/flutter_style_transfer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # image_gallery_saver: ^1.6.8
  dio: ^4.0.0
  package_info: ^2.0.0
  image_gallery_saver:
    git:
      url: https://github.com/fzyzcjy/image_gallery_saver.git
      ref: master
  json_annotation: ^4.0.1
  sembast: ^3.0.0+4
  equatable: ^2.0.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.2
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  image: ^3.0.2
  multi_image_picker: ^4.8.0
  tflite_flutter: ^0.6.0
  simple_animations: ^3.0.3
  flutter_slidable: ^0.6.0-nullsafety.0
  freezed_annotation: ^0.14.1
  extended_image: ^4.0.0
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^4.1.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/images/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/